version: "3.8"

services:
  database:
    image: postgres:latest
    container_name: postgresnodejs
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DATABASE=${DB_NAME}
    volumes:
      - db_data:/data/postgresql

volumes:
  db_data:
