version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apinodejs
    restart: on-failure
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - mongodb
    links: 
      - mongodb
    environment:
      MONGO_INITDB_USERNAME: ${MONGO_USER}
      MONGO_INITDB_PASSWORD: ${MONGO_PWD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

  mongodb:
    extends:
      file: docker-compose.base.yml
      service: mongodb

volumes:
  node_modules:
  mongodb_data:
