version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apinodejs
    restart: on-failure
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - database
    links: 
      - database
    environment:
      DB_HOST: database
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}

  database:
    extends:
      file: docker-compose.base.yml
      service: database

volumes:
  node_modules:
  db_data:
