version: "3.8"

services:
    mongodb:
        image: mongo:4.0
        container_name: mongodb
        ports: 
            - ${MONGO_PORT}:27017
        environment: 
            MONGO_INITDB_USERNAME: ${MONGO_USER}
            MONGO_INITDB_PASSWORD: ${MONGO_PWD}
            MONGO_INITDB_DATABASE: ${MONGO_DB}
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data:
